<a href="https://colab.research.google.com/github/hisan/myleetcode/blob/master/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Learning-OpenCV-4-Computer-Vision-with-Python-3

## Chapter 2: Handling Files, Cameras, and GUIs

In [2]:
import numpy
import cv2

img = numpy.zeros((3, 3), dtype=numpy.uint8)
print(img)
print("----------------\n")
img2 = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
print(img2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
----------------

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


如上示例,演示了一个3x3的 `Grayscale Image` 和 3x3x3的 `Color Image` in BGR(Blue, Green, Red) format.

### `Grayscale Image` and `Color Image`:
| **Grayscale**                        | **BGR (Color)**                     |
|--------------------------------------|-------------------------------------|
| Requires less memory (1 byte/pixel). | Requires more memory (3 bytes/pixel). |
| Used for tasks where color is not important (e.g., edge detection, thresholding). | Required for tasks involving color analysis (e.g., object detection, color segmentation). |
| Simpler to process and faster for computation. | More information for advanced processing. |
| Not suitable for applications requiring color. | Suitable for color-dependent tasks. |

pixels: 3x3 = 9 <==> Width x Height
所以通常说的1920x1080分辨率,即 2073600 个pixels. 即像素点越多图像越清晰.

而对于灰度图来说, 用一个byte来表示一个pixel. 而对于颜色图, 则是3个color channel表示一个pixel, 每个color channel用一个byte来表示.

如上img2:
~~~sh
img2 = [
    [[0, 0, 0], [0, 0, 0], [0, 0, 0]],  # Row 0
    [[0, 0, 0], [0, 0, 0], [0, 0, 0]],  # Row 1
    [[0, 0, 0], [0, 0, 0], [0, 0, 0]]   # Row 2
]
~~~
row x column x channel:
即三行,每行三列,每列一个Pixel,由三个color channel组成.

img2[0][0] 表示一个pixel.
img2[0][0][0]: Blue channel value for the pixel.
img2[0][0][1]: Green channel value for the pixel.
img2[0][0][2]: Red channel value for the pixel.

使用3x3x3的array来生成Color image的示例

In [5]:
import numpy as np
import cv2
from google.colab.patches import cv2_imshow  # Use this only for Google Colab

# Create a 20x20x3 array representing the image
img = np.zeros((20, 20, 3), dtype=np.uint8)

# Fill the top-left (10x10) with red
img[:10, :10] = [0, 0, 255]  # Red (BGR)

# Fill the top-right (10x10) with green
img[:10, 10:] = [0, 255, 0]  # Green (BGR)

# Fill the bottom-left (10x10) with blue
img[10:, :10] = [255, 0, 0]  # Blue (BGR)

# Fill the bottom-right (10x10) with yellow
img[10:, 10:] = [0, 255, 255]  # Yellow (BGR)

# Display the image
cv2_imshow(img)  # For Google Colab
# cv2.imshow("20x20 Color Icon", img)  # Use this for local machines
