<a href="https://colab.research.google.com/github/hisan/myleetcode/blob/master/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Learning-OpenCV-4-Computer-Vision-with-Python-3

## Chapter 2: Handling Files, Cameras, and GUIs

a multidimensional array; it has columns and rows of pixels, and each pixel has a value, represented by a single 8-bit integer:
    0 is black, 255 is white

In [2]:
import numpy
import cv2

img = numpy.zeros((3, 3), dtype=numpy.uint8)
print(img)
print("----------------\n")
img2 = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
print(img2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
----------------

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


如上示例,演示了一个3x3的 `Grayscale Image` 和 3x3x3的 `Color Image` in BGR(Blue, Green, Red) format.

### `Grayscale Image` and `Color Image`:
| **Grayscale**                        | **BGR (Color)**                     |
|--------------------------------------|-------------------------------------|
| Requires less memory (1 byte/pixel). | Requires more memory (3 bytes/pixel). |
| Used for tasks where color is not important (e.g., edge detection, thresholding). | Required for tasks involving color analysis (e.g., object detection, color segmentation). |
| Simpler to process and faster for computation. | More information for advanced processing. |
| Not suitable for applications requiring color. | Suitable for color-dependent tasks. |

pixels: 3x3 = 9 <==> Width x Height
所以通常说的1920x1080分辨率,即 2073600 个pixels. 即像素点越多图像越清晰.

而对于灰度图来说, 用一个byte来表示一个pixel. 而对于颜色图, 则是3个color channel表示一个pixel, 每个color channel用一个byte来表示.

如上img2:
~~~sh
img2 = [
    [[0, 0, 0], [0, 0, 0], [0, 0, 0]],  # Row 0
    [[0, 0, 0], [0, 0, 0], [0, 0, 0]],  # Row 1
    [[0, 0, 0], [0, 0, 0], [0, 0, 0]]   # Row 2
]
~~~
row x column x channel:
即三行,每行三列,每列一个Pixel,由三个color channel组成.

img2[0][0] 表示一个pixel.
img2[0][0][0]: Blue channel value for the pixel.
img2[0][0][1]: Green channel value for the pixel.
img2[0][0][2]: Red channel value for the pixel.

使用3x3x3的array来生成Color image的示例

In [5]:
import numpy as np
import cv2
from google.colab.patches import cv2_imshow  # Use this only for Google Colab

# Create a 20x20x3 array representing the image
img = np.zeros((20, 20, 3), dtype=np.uint8)

# Fill the top-left (10x10) with red
img[:10, :10] = [0, 0, 255]  # Red (BGR)

# Fill the top-right (10x10) with green
img[:10, 10:] = [0, 255, 0]  # Green (BGR)

# Fill the bottom-left (10x10) with blue
img[10:, :10] = [255, 0, 0]  # Blue (BGR)

# Fill the bottom-right (10x10) with yellow
img[10:, 10:] = [0, 255, 255]  # Yellow (BGR)

# Display the image
cv2_imshow(img)  # For Google Colab
# cv2.imshow("20x20 Color Icon", img)  # Use this for local machines


如上输出,输出了一个小图像.

Basic I/O scripts 21
Reading/writing an image file 22
Converting between an image and raw bytes 24
Accessing image data with numpy.array 26
Reading/writing a video file 28
Capturing camera frames 29
Displaying images in a window 31
Displaying camera frames in a window 32
Project Cameo (face tracking and image manipulation) 34
Table of Contents[ ii ]
Cameo – an object-oriented design 35
Abstracting a video stream with managers.CaptureManager 35
Abstracting a window and keyboard with managers.WindowManager 41
Applying everything with cameo.Cameo 42
Summary 44
### Chapter 3: Processing Images with OpenCV 3 45
Converting between different color spaces 45
A quick note on BGR 46
The Fourier Transform 46
High pass filter 47
Low pass filter 49
Creating modules 49
Edge detection 49
Custom kernels – getting convoluted 51
Modifying the application 53
Edge detection with Canny 55
Contour detection 56
Contours – bounding box, minimum area rectangle,
and minimum enclosing circle 57
Contours – convex contours and the Douglas-Peucker algorithm 60
Line and circle detection 62
Line detection 62
Circle detection 63
Detecting shapes 64
Summary 65
### Chapter 4: Depth Estimation and Segmentation 67
Creating modules 67
Capturing frames from a depth camera 68
Creating a mask from a disparity map 71
Masking a copy operation 72
Depth estimation with a normal camera 74
Object segmentation using the Watershed and GrabCut algorithms 80
Example of foreground detection with GrabCut 82
Image segmentation with the Watershed algorithm 84
Summary 87
### Chapter 5: Detecting and Recognizing Faces 89
Conceptualizing Haar cascades 90
Getting Haar cascade data 91
Using OpenCV to perform face detection 91
Performing face detection on a still image 92
Table of Contents[ iii ]
Performing face detection on a video 94
Performing face recognition 97
Generating the data for face recognition 98
Recognizing faces 100
Preparing the training data 101
Loading the data and recognizing faces 102
Performing an Eigenfaces recognition 103
Performing face recognition with Fisherfaces 105
Performing face recognition with LBPH 106
Discarding results with confidence score 106
Summary 107
### Chapter 6: Retrieving Images and Searching
Using Image Descriptors 109
Feature detection algorithms 109
Defining features 110
Detecting features – corners 110
Feature extraction and description using DoG and SIFT 113
Anatomy of a keypoint 116
Feature extraction and detection using Fast Hessian and SURF 117
ORB feature detection and feature matching 120
FAST 120
BRIEF 121
Brute-Force matching 121
Feature matching with ORB 122
Using K-Nearest Neighbors matching 125
FLANN-based matching 126
FLANN matching with homography 130
A sample application – tattoo forensics 133
Saving image descriptors to file 133
Scanning for matches 134
Summary 137
### Chapter 7: Detecting and Recognizing Objects 139
Object detection and recognition techniques 139
HOG descriptors 140
The scale issue 142
The location issue 142
Non-maximum (or non-maxima) suppression 145
Support vector machines 146
People detection 147
Creating and training an object detector 149
Bag-of-words 149
BOW in computer vision 150
Detecting cars 153
What did we just do? 155
Table of Contents[ iv ]
SVM and sliding windows 160
Example – car detection in a scene 161
Dude, where's my car? 171
Summary 175
### Chapter 8: Tracking Objects 177
Detecting moving objects 177
Basic motion detection 178
Background subtractors – KNN, MOG2, and GMG 181
Meanshift and CAMShift 185
Color histograms 188
The calcHist function 189
The calcBackProject function 190
In summary 190
Back to the code 191
CAMShift 193
The Kalman filter 194
Predict and update 195
An example 196
A real-life example – tracking pedestrians 199
The application workflow 200
A brief digression – functional versus object-oriented programming 200
The Pedestrian class 202
The main program 205
Where do we go from here? 207
Summary 208

### Chapter 9: Neural Networks with OpenCV – an Introduction 209
Artificial neural networks 209
Neurons and perceptrons 210
The structure of an ANN 211
Network layers by example 212
The input layer 212
The output layer 212
The hidden layer 212
ANNs in OpenCV 214
ANN-imal classification 216
Training epochs 220
Handwritten digit recognition with ANNs 222
MNIST – the handwritten digit database 222
Customized training data 222
The initial parameters 222
The input layer 222
The hidden layer 223
The output layer 223
Table of Contents[ v ]
Training epochs 223
Other parameters 223
Mini-libraries 224
The main file 228
Possible improvements and potential applications 234
Improvements 234
Potential applications 235
Summary 235
To boldly go… 235

## progress
date | process | time segments | sum
-|-|-|-
2024-08-19 | created md | 16:30~ |
2024-11-26 | 2ch start | 15:00 ~ |

~~~py
~~~

out:
~~~sh
~~~