<a href="https://colab.research.google.com/github/hisan/myleetcode/blob/master/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Learning-OpenCV-4-Computer-Vision-with-Python-3

## Chapter 2: Handling Files, Cameras, and GUIs

In [3]:
import numpy
import cv2

img = numpy.zeros((3, 3), dtype=numpy.uint8)
print(img)
print("----------------\n")
img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
print(img)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
----------------

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
